/* FICHIER TABLEAU.JAVA :
 *  FICHIER DE CREATION DU TABLEAU DE STRATEGIE
 *      
 * 
 *  DERNIÈRE MÀJ : 09/04/2019 par JULIE BALOUET
 *  CRÉÉ PAR MORGANE BOUCHARD
 *  2018/2019
 * ------------------------------------------
 *  INFOS :
 *      - CLASSE TABLEAU
 * ------------------------------------------
 */

package blackjack;
 
/** Tableau de stratégie
 * @author Morgane BOUCHARD
 */
public class Tableau
{
    private static Strategie[][] tableau_strategie;
     
    /** Initialisation du tableau
     * @author Morgane BOUCHARD
     */
    public static void init()
    {
        tableau_strategie = new Strategie [36][10]; 
        
        tableau_strategie [0][0]= Strategie.RESTER  ;tableau_strategie [0][1]= Strategie.RESTER ;tableau_strategie [0][2]= Strategie.RESTER;tableau_strategie [0][3]= Strategie.RESTER ;tableau_strategie [0][4]= Strategie.RESTER ;tableau_strategie [0][5]= Strategie.RESTER ;tableau_strategie [0][6]= Strategie.RESTER ;tableau_strategie [0][7]= Strategie.RESTER ;tableau_strategie [0][8]= Strategie.RESTER ;tableau_strategie [0][9]= Strategie.RESTER ;
        tableau_strategie [1][0]= Strategie.RESTER ;tableau_strategie [1][1]= Strategie.RESTER ;tableau_strategie [1][2]= Strategie.RESTER ;tableau_strategie [1][3]= Strategie.RESTER ;tableau_strategie [1][4]= Strategie.RESTER ;tableau_strategie [1][5]= Strategie.RESTER ;tableau_strategie [1][6]= Strategie.RESTER ;tableau_strategie [1][7]= Strategie.RESTER ;tableau_strategie [1][8]= Strategie.RESTER ;tableau_strategie [1][9]= Strategie.RESTER ;
        tableau_strategie [2][0]= Strategie.RESTER ;tableau_strategie [2][1]= Strategie.RESTER ;tableau_strategie [2][2]= Strategie.RESTER ;tableau_strategie [2][3]= Strategie.RESTER ;tableau_strategie [2][4]= Strategie.RESTER ;tableau_strategie [2][5]= Strategie.RESTER ;tableau_strategie [2][6]= Strategie.RESTER ;tableau_strategie [2][7]= Strategie.RESTER ;tableau_strategie [2][8]= Strategie.RESTER ;tableau_strategie [2][9]= Strategie.RESTER ;
        tableau_strategie [3][0]= Strategie.RESTER ;tableau_strategie [3][1]= Strategie.RESTER ;tableau_strategie [3][2]= Strategie.RESTER ;tableau_strategie [3][3]= Strategie.RESTER ;tableau_strategie [3][4]= Strategie.RESTER ;tableau_strategie [3][5]= Strategie.RESTER ;tableau_strategie [3][6]= Strategie.RESTER ;tableau_strategie [3][7]= Strategie.RESTER ;tableau_strategie [3][8]= Strategie.RESTER ;tableau_strategie [3][9]= Strategie.RESTER ;
        tableau_strategie [4][0]= Strategie.RESTER ;tableau_strategie [4][1]= Strategie.RESTER ;tableau_strategie [4][2]= Strategie.RESTER ;tableau_strategie [4][3]= Strategie.RESTER ;tableau_strategie [4][4]= Strategie.RESTER ;tableau_strategie [4][5]= Strategie.RESTER ;tableau_strategie [4][6]= Strategie.RESTER ;tableau_strategie [4][7]= Strategie.RESTER ;tableau_strategie [4][8]= Strategie.RESTER ;tableau_strategie [4][9]= Strategie.RESTER ;
        tableau_strategie [5][0]= Strategie.RESTER ;tableau_strategie [5][1]= Strategie.RESTER ;tableau_strategie [5][2]= Strategie.RESTER ;tableau_strategie [5][3]= Strategie.RESTER ;tableau_strategie [5][4]= Strategie.RESTER ;tableau_strategie [5][5]= Strategie.TIRER ;tableau_strategie [5][6]= Strategie.TIRER ;tableau_strategie [5][7]= Strategie.TIRER ;tableau_strategie [5][8]= Strategie.TIRER;tableau_strategie [5][9]= Strategie.TIRER ;
        tableau_strategie [6][0]= Strategie.RESTER ;tableau_strategie [6][1]= Strategie.RESTER ;tableau_strategie [6][2]= Strategie.RESTER ;tableau_strategie [6][3]= Strategie.RESTER ;tableau_strategie [6][4]= Strategie.RESTER ;tableau_strategie [6][5]= Strategie.TIRER ;tableau_strategie [6][6]= Strategie.TIRER ;tableau_strategie [6][7]= Strategie.TIRER ;tableau_strategie [6][8]= Strategie.TIRER ;tableau_strategie [6][9]= Strategie.TIRER ;
        tableau_strategie [7][0]= Strategie.RESTER ;tableau_strategie [7][1]= Strategie.RESTER ;tableau_strategie [7][2]= Strategie.RESTER ;tableau_strategie [7][3]= Strategie.RESTER ;tableau_strategie [7][4]= Strategie.RESTER ;tableau_strategie [7][5]= Strategie.TIRER ;tableau_strategie [7][6]= Strategie.TIRER ;tableau_strategie [7][7]= Strategie.TIRER ;tableau_strategie [7][8]= Strategie.TIRER ;tableau_strategie [7][9]= Strategie.TIRER ;
        tableau_strategie [8][0]= Strategie.RESTER ;tableau_strategie [8][1]= Strategie.RESTER ;tableau_strategie [8][2]= Strategie.RESTER ;tableau_strategie [8][3]= Strategie.RESTER ;tableau_strategie [8][4]= Strategie.RESTER ;tableau_strategie [8][5]= Strategie.TIRER ;tableau_strategie [8][6]= Strategie.TIRER ;tableau_strategie [8][7]= Strategie.TIRER ;tableau_strategie [8][8]= Strategie.TIRER ;tableau_strategie [8][9]= Strategie.TIRER ;
        tableau_strategie [9][0]= Strategie.TIRER ;tableau_strategie [9][1]= Strategie.TIRER ;tableau_strategie [9][2]= Strategie.RESTER ;tableau_strategie [9][3]= Strategie.RESTER ;tableau_strategie [9][4]= Strategie.RESTER ;tableau_strategie [9][5]= Strategie.TIRER ;tableau_strategie [9][6]= Strategie.TIRER ;tableau_strategie [9][7]= Strategie.TIRER ;tableau_strategie [9][8]= Strategie.TIRER ;tableau_strategie [9][9]= Strategie.TIRER ;
        tableau_strategie [10][0]= Strategie.DOUBLER ;tableau_strategie [10][1]= Strategie.DOUBLER ;tableau_strategie [10][2]= Strategie.DOUBLER ;tableau_strategie [10][3]= Strategie.DOUBLER ;tableau_strategie [10][4]= Strategie.DOUBLER ;tableau_strategie [10][5]= Strategie.DOUBLER ;tableau_strategie [10][6]= Strategie.DOUBLER;tableau_strategie [10][7]= Strategie.DOUBLER ;tableau_strategie[10][8]= Strategie.TIRER ;tableau_strategie [10][9]= Strategie.TIRER ;
        tableau_strategie [11][0]= Strategie.DOUBLER ;tableau_strategie [11][1]= Strategie.DOUBLER ;tableau_strategie [11][2]= Strategie.DOUBLER ;tableau_strategie [11][3]= Strategie.DOUBLER ;tableau_strategie [11][4]= Strategie.DOUBLER ;tableau_strategie [11][5]= Strategie.DOUBLER ;tableau_strategie [11][6]= Strategie.DOUBLER;tableau_strategie [11][7]= Strategie.DOUBLER ;tableau_strategie[11][8]= Strategie.TIRER ;tableau_strategie [11][9]= Strategie.TIRER ;
        tableau_strategie [12][0]= Strategie.TIRER ;tableau_strategie [12][1]= Strategie.DOUBLER ;tableau_strategie [12][2]= Strategie.DOUBLER ;tableau_strategie [12][3]= Strategie.DOUBLER ;tableau_strategie [12][4]= Strategie.DOUBLER ;tableau_strategie [12][5]= Strategie.TIRER ;tableau_strategie [12][6]= Strategie.TIRER;tableau_strategie [12][7]= Strategie.TIRER ;tableau_strategie[12][8]= Strategie.TIRER ;tableau_strategie [12][9]= Strategie.TIRER ;
        tableau_strategie [13][0]= Strategie.TIRER ;tableau_strategie [13][1]= Strategie.TIRER ;tableau_strategie [13][2]= Strategie.TIRER ;tableau_strategie [13][3]= Strategie.TIRER;tableau_strategie [13][4]= Strategie.TIRER;tableau_strategie [13][5]= Strategie.TIRER ;tableau_strategie [13][6]= Strategie.TIRER;tableau_strategie [13][7]= Strategie.TIRER;tableau_strategie[13][8]= Strategie.TIRER ;tableau_strategie [13][9]= Strategie.TIRER ;
        tableau_strategie [14][0]= Strategie.TIRER ;tableau_strategie [14][1]= Strategie.TIRER ;tableau_strategie [14][2]= Strategie.TIRER ;tableau_strategie [14][3]= Strategie.TIRER;tableau_strategie [14][4]= Strategie.TIRER;tableau_strategie [14][5]= Strategie.TIRER ;tableau_strategie [14][6]= Strategie.TIRER;tableau_strategie [14][7]= Strategie.TIRER;tableau_strategie[14][8]= Strategie.TIRER ;tableau_strategie [14][9]= Strategie.TIRER ;
        tableau_strategie [15][0]= Strategie.TIRER ;tableau_strategie [15][1]= Strategie.TIRER ;tableau_strategie [15][2]= Strategie.TIRER ;tableau_strategie [15][3]= Strategie.TIRER;tableau_strategie [15][4]= Strategie.TIRER;tableau_strategie [15][5]= Strategie.TIRER ;tableau_strategie [15][6]= Strategie.TIRER;tableau_strategie [15][7]= Strategie.TIRER;tableau_strategie[15][8]= Strategie.TIRER ;tableau_strategie [15][9]= Strategie.TIRER ;
        tableau_strategie [16][0]= Strategie.TIRER ;tableau_strategie [16][1]= Strategie.TIRER ;tableau_strategie [16][2]= Strategie.TIRER ;tableau_strategie [16][3]= Strategie.TIRER;tableau_strategie [16][4]= Strategie.TIRER;tableau_strategie [16][5]= Strategie.TIRER ;tableau_strategie [16][6]= Strategie.TIRER;tableau_strategie [16][7]= Strategie.TIRER;tableau_strategie[16][8]= Strategie.TIRER ;tableau_strategie [16][9]= Strategie.TIRER ;
        tableau_strategie [17][0]= Strategie.PARTAGER ;tableau_strategie [17][1]= Strategie.PARTAGER ;tableau_strategie [17][2]= Strategie.PARTAGER ;tableau_strategie [17][3]= Strategie.PARTAGER;tableau_strategie [17][4]= Strategie.PARTAGER;tableau_strategie [17][5]= Strategie.PARTAGER ;tableau_strategie [17][6]= Strategie.PARTAGER;tableau_strategie [17][7]= Strategie.PARTAGER;tableau_strategie[17][8]= Strategie.PARTAGER ;tableau_strategie [17][9]= Strategie.TIRER ;
        tableau_strategie [18][0]= Strategie.RESTER  ;tableau_strategie [18][1]= Strategie.RESTER ;tableau_strategie [18][2]= Strategie.RESTER;tableau_strategie [18][3]= Strategie.RESTER ;tableau_strategie [18][4]= Strategie.RESTER ;tableau_strategie [18][5]= Strategie.RESTER ;tableau_strategie [18][6]= Strategie.RESTER ;tableau_strategie [18][7]= Strategie.RESTER ;tableau_strategie [18][8]= Strategie.RESTER ;tableau_strategie [18][9]= Strategie.RESTER ;
        tableau_strategie [19][0]= Strategie.PARTAGER ;tableau_strategie [19][1]= Strategie.PARTAGER ;tableau_strategie [19][2]= Strategie.PARTAGER ;tableau_strategie [19][3]= Strategie.PARTAGER;tableau_strategie [19][4]= Strategie.PARTAGER;tableau_strategie [19][5]= Strategie.RESTER ;tableau_strategie [19][6]= Strategie.PARTAGER;tableau_strategie [19][7]= Strategie.PARTAGER;tableau_strategie[19][8]= Strategie.RESTER ;tableau_strategie [19][9]= Strategie.RESTER ;
        tableau_strategie [20][0]= Strategie.PARTAGER ;tableau_strategie [20][1]= Strategie.PARTAGER ;tableau_strategie [20][2]= Strategie.PARTAGER ;tableau_strategie [20][3]= Strategie.PARTAGER;tableau_strategie [20][4]= Strategie.PARTAGER;tableau_strategie [20][5]= Strategie.PARTAGER ;tableau_strategie [20][6]= Strategie.PARTAGER;tableau_strategie [20][7]= Strategie.PARTAGER;tableau_strategie[20][8]= Strategie.TIRER ;tableau_strategie [20][9]= Strategie.TIRER ;
        tableau_strategie [21][0]= Strategie.PARTAGER ;tableau_strategie [21][1]= Strategie.PARTAGER ;tableau_strategie [21][2]= Strategie.PARTAGER ;tableau_strategie [21][3]= Strategie.PARTAGER;tableau_strategie [21][4]= Strategie.PARTAGER;tableau_strategie [21][5]= Strategie.PARTAGER ;tableau_strategie [21][6]= Strategie.TIRER;tableau_strategie [21][7]= Strategie.TIRER;tableau_strategie[21][8]= Strategie.TIRER ;tableau_strategie [21][9]= Strategie.TIRER ;
        tableau_strategie [22][0]= Strategie.PARTAGER ;tableau_strategie [22][1]= Strategie.PARTAGER ;tableau_strategie [22][2]= Strategie.PARTAGER ;tableau_strategie [22][3]= Strategie.PARTAGER;tableau_strategie [22][4]= Strategie.PARTAGER;tableau_strategie [22][5]= Strategie.TIRER ;tableau_strategie [22][6]= Strategie.TIRER;tableau_strategie [22][7]= Strategie.TIRER;tableau_strategie[22][8]= Strategie.TIRER ;tableau_strategie [22][9]= Strategie.TIRER ;
        tableau_strategie [23][0]= Strategie.DOUBLER ;tableau_strategie [23][1]= Strategie.DOUBLER;tableau_strategie [23][2]= Strategie.DOUBLER ;tableau_strategie [23][3]= Strategie.DOUBLER;tableau_strategie [23][4]= Strategie.DOUBLER;tableau_strategie [23][5]= Strategie.DOUBLER ;tableau_strategie [23][6]= Strategie.DOUBLER;tableau_strategie [23][7]= Strategie.DOUBLER;tableau_strategie[23][8]= Strategie.TIRER ;tableau_strategie [23][9]= Strategie.TIRER ;
        tableau_strategie [24][0]= Strategie.TIRER ;tableau_strategie [24][1]= Strategie.TIRER ;tableau_strategie [24][2]= Strategie.TIRER ;tableau_strategie [24][3]= Strategie.PARTAGER;tableau_strategie [24][4]= Strategie.PARTAGER;tableau_strategie [24][5]= Strategie.TIRER ;tableau_strategie [24][6]= Strategie.TIRER;tableau_strategie [24][7]= Strategie.TIRER;tableau_strategie[24][8]= Strategie.TIRER ;tableau_strategie [24][9]= Strategie.TIRER ;
        tableau_strategie [25][0]= Strategie.PARTAGER ;tableau_strategie [25][1]= Strategie.PARTAGER ;tableau_strategie [25][2]= Strategie.PARTAGER ;tableau_strategie [25][3]= Strategie.PARTAGER;tableau_strategie [25][4]= Strategie.PARTAGER;tableau_strategie [25][5]= Strategie.PARTAGER ;tableau_strategie [25][6]= Strategie.TIRER;tableau_strategie [25][7]= Strategie.TIRER;tableau_strategie[25][8]= Strategie.TIRER ;tableau_strategie [25][9]= Strategie.TIRER ;
        tableau_strategie [26][0]= Strategie.PARTAGER ;tableau_strategie [26][1]= Strategie.PARTAGER ;tableau_strategie [26][2]= Strategie.PARTAGER ;tableau_strategie [26][3]= Strategie.PARTAGER;tableau_strategie [26][4]= Strategie.PARTAGER;tableau_strategie [26][5]= Strategie.PARTAGER ;tableau_strategie [26][6]= Strategie.TIRER;tableau_strategie [26][7]= Strategie.TIRER;tableau_strategie[26][8]= Strategie.TIRER ;tableau_strategie [26][9]= Strategie.TIRER ;
        tableau_strategie [27][0]= Strategie.RESTER  ;tableau_strategie [27][1]= Strategie.RESTER ;tableau_strategie [27][2]= Strategie.RESTER;tableau_strategie [27][3]= Strategie.RESTER ;tableau_strategie [27][4]= Strategie.RESTER ;tableau_strategie [27][5]= Strategie.RESTER ;tableau_strategie [27][6]= Strategie.RESTER ;tableau_strategie [27][7]= Strategie.RESTER ;tableau_strategie [27][8]= Strategie.RESTER ;tableau_strategie [27][9]= Strategie.RESTER ;
        tableau_strategie [28][0]= Strategie.RESTER  ;tableau_strategie [28][1]= Strategie.RESTER ;tableau_strategie [28][2]= Strategie.RESTER;tableau_strategie [28][3]= Strategie.RESTER ;tableau_strategie [28][4]= Strategie.RESTER ;tableau_strategie [28][5]= Strategie.RESTER ;tableau_strategie [28][6]= Strategie.RESTER ;tableau_strategie [28][7]= Strategie.RESTER ;tableau_strategie [28][8]= Strategie.RESTER ;tableau_strategie [28][9]= Strategie.RESTER ;
        tableau_strategie [29][0]= Strategie.RESTER  ;tableau_strategie [29][1]= Strategie.RESTER ;tableau_strategie [29][2]= Strategie.RESTER;tableau_strategie [29][3]= Strategie.RESTER ;tableau_strategie [29][4]= Strategie.RESTER ;tableau_strategie [29][5]= Strategie.RESTER ;tableau_strategie [29][6]= Strategie.RESTER ;tableau_strategie [29][7]= Strategie.RESTER ;tableau_strategie [29][8]= Strategie.RESTER ;tableau_strategie [29][9]= Strategie.RESTER ;
        tableau_strategie [30][0]= Strategie.RESTER  ;tableau_strategie [30][1]= Strategie.DOUBLER ;tableau_strategie [30][2]= Strategie.DOUBLER;tableau_strategie [30][3]= Strategie.DOUBLER ;tableau_strategie [30][4]= Strategie.DOUBLER ;tableau_strategie [30][5]= Strategie.RESTER ;tableau_strategie [30][6]= Strategie.RESTER ;tableau_strategie [30][7]= Strategie.TIRER ;tableau_strategie [30][8]= Strategie.TIRER ;tableau_strategie [30][9]= Strategie.TIRER;
        tableau_strategie [31][0]= Strategie.TIRER ;tableau_strategie [31][1]= Strategie.DOUBLER ;tableau_strategie [31][2]= Strategie.DOUBLER;tableau_strategie [31][3]= Strategie.DOUBLER ;tableau_strategie [31][4]= Strategie.DOUBLER ;tableau_strategie [31][5]=Strategie.TIRER ;tableau_strategie [31][6]=Strategie.TIRER ;tableau_strategie [31][7]= Strategie.TIRER ;tableau_strategie [31][8]= Strategie.TIRER ;tableau_strategie [31][9]= Strategie.TIRER;
        tableau_strategie [32][0]= Strategie.TIRER ;tableau_strategie [32][1]= Strategie.TIRER ;tableau_strategie [32][2]= Strategie.DOUBLER;tableau_strategie [32][3]= Strategie.DOUBLER ;tableau_strategie [32][4]= Strategie.DOUBLER ;tableau_strategie [32][5]=Strategie.TIRER ;tableau_strategie [32][6]=Strategie.TIRER ;tableau_strategie [32][7]= Strategie.TIRER ;tableau_strategie [32][8]= Strategie.TIRER ;tableau_strategie [32][9]= Strategie.TIRER;
        tableau_strategie [33][0]= Strategie.TIRER ;tableau_strategie [33][1]= Strategie.TIRER ;tableau_strategie [33][2]= Strategie.DOUBLER;tableau_strategie [33][3]= Strategie.DOUBLER ;tableau_strategie [33][4]= Strategie.DOUBLER ;tableau_strategie [33][5]=Strategie.TIRER ;tableau_strategie [33][6]=Strategie.TIRER ;tableau_strategie [33][7]= Strategie.TIRER ;tableau_strategie [33][8]= Strategie.TIRER ;tableau_strategie [33][9]= Strategie.TIRER;
        tableau_strategie [34][0]= Strategie.TIRER ;tableau_strategie [34][1]= Strategie.TIRER ;tableau_strategie [34][2]= Strategie.TIRER;tableau_strategie [34][3]= Strategie.DOUBLER ;tableau_strategie [34][4]= Strategie.DOUBLER ;tableau_strategie [34][5]=Strategie.TIRER ;tableau_strategie [34][6]=Strategie.TIRER ;tableau_strategie [34][7]= Strategie.TIRER ;tableau_strategie [34][8]= Strategie.TIRER ;tableau_strategie [34][9]= Strategie.TIRER;
        tableau_strategie [35][0]= Strategie.TIRER ;tableau_strategie [35][1]= Strategie.TIRER ;tableau_strategie [35][2]= Strategie.TIRER;tableau_strategie [35][3]= Strategie.DOUBLER ;tableau_strategie [35][4]= Strategie.DOUBLER ;tableau_strategie [35][5]=Strategie.TIRER ;tableau_strategie [35][6]=Strategie.TIRER ;tableau_strategie [35][7]= Strategie.TIRER ;tableau_strategie [35][8]= Strategie.TIRER ;tableau_strategie [35][9]= Strategie.TIRER;
    }

    /**
	 * Retourne le tableau de stratégie
     * @author Morgane BOUCHARD
     * @return Le tableau de stratégie
	*/
    public static Strategie[][] getTabStrategie()
    {
        return tableau_strategie;
    }
}
